# docker-compose.yml
version: '3'
services:
  app:
    build:
      context: ./
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/drawings-db
      NODE_ENV: development
      PORT: 8080
    ports:
      - '8080:8080'
    command: npm run start
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: drawings-db
